# This is a YAML config file for Individual CycleWays project

# Web server variables

db:
  db_name: "<your_db_name>"
  db_user: "<your_db_user>"
  db_password: "<your_db_password>"
  db_host: "<your_db_host>"

path:
  log: "<your_path_to_log_file>"
  csv_path: "<your_path_to_csv_file>"
  meta_path: "<your_path_to_meta_file>"

api:
  api_key: "<your_api_key>"
  api_url: "<your_source_api_url>"






